### ISSUE TITLE
Animation category?

### ISSUE THREAD

**Issue by SachaG** [bestofjs/javascript-risingstars#12]
Should we have Animation libraries as a separate category? https://bestof.js.org/tags/animation/

**Comment by michaelrambeau** [comment]
Why not, but besides the newcomer`Popmotion`, I don't really find the category very "attractive".

The TOP 5 (https://bestof.js.org/tags/animation/trending/last-12-months) would be:

* Animate.css
* Animate.js
* React Motion
* Pop Motion
* mo.js

Only Popmotion has its own `org` (other repo show just their creator's avatar).

If I had to add one category I would add the `CSS Toolkit` because all developers know what it means, or know Bootstrap at least.

Or we could add both of them, I'm not sold to anything, just giving my point of view...

**Comment by SachaG** [comment]
Ok never mind then. I just thought of it because I saw Popmotion mentioned in another roundup.
