### ISSUE TITLE
How to add `create-react-native-app` and `react-navigation` projects?

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/javascript-risingstars#21]
On [Twitter](https://twitter.com/notbrent/status/952000423153475584), Brent Vatne ([GitHub profile](https://github.com/brentvatne)) told us that we should include 2 projects among the "React Ecosystem" projects:

* https://github.com/react-community/create-react-native-app
* https://github.com/react-navigation/react-navigation

![image](https://user-images.githubusercontent.com/5546996/34912113-a3b785bc-f91b-11e7-922d-5b199e13a9c3.png)

In _Best of JS_, these 2 projects are tagged under `React Native` tag and not under `React`, that's why they don't show up in _Rising Stars_.

So we have 2 options.

### Option A

Include also `React Native` projects in the "React ecosystem" category

Doing this, and exluding both `React` and `React Native` projects, the TOP 10 would change like this:

![image](https://user-images.githubusercontent.com/5546996/34912094-f6889890-f91a-11e7-912d-875a6ddf138f.png)

No more `React Boilerplate` and `Recompose`, that are mentioned in the comments.

That's why we could show more projects maybe, 15 instead of 10, for example.

### Option B

Add a React Native category... but we would have to add comments.

**Comment by brentvatne** [comment]
I'm leaning towards option A, but I don't have a very strong preference. Showing 15 projects instead of 10 could make sense because there have been a lot of interesting projects in the React ecosystem over the last year, and the React ecosystem includes web, native, and other render targets.

If we add a React Native category we'd have to add some of the React Ecosystem libraries to the list too, or it wouldn't make much sense (StoryBook, React Router, Recompose are all cross-platform). We'd also need to add React Navigation to both because it supports web. As a result, the top libraries would be almost half duplicates between React Ecosystem and React Native.

Another small yak shave -- I wonder if we are missing other libraries from the React Native list from the Best of JS website here. One that comes to mind is [React Native Web](https://github.com/necolas/react-native-web).

Last yak shave, perhaps it is reasonable to combine Ant Design, Ant Design Pro, and Ant Design Mobile under one entry? If not, the results are skewed a bit because many libraries use a monorepo approach (eg: React Router has a packages directory which includes the base library, DOM, Native and others under one repo).

**Comment by michaelrambeau** [comment]
Thank you very much @brentvatne 
We updated the "React Ecosystem" to include both "React" and "React Native" projects.
Could you let us know it's OK for you, now?

By the way, if you wanted to write comments about the React ecosystem, we would be very proud to mention you as "Guest Writer", like we did with Evan You 😉 .

**Comment by brentvatne** [comment]
hey @michaelrambeau - looks great. I could add a comment here if you like, I think it's probably fine as it is though :)

**Comment by michaelrambeau** [comment]
Thank you for having checked Brent @brentvatne 
Next year, if you don't mind, I will ask you the comments about the "React Ecosystem" category... be patient! 😄

**Comment by brentvatne** [comment]
sounds good!
