### ISSUE TITLE
Add Angular Ecosystem

### ISSUE THREAD

**Issue by BBlackwo** [bestofjs/javascript-risingstars#32]
Hey I love your rising stars page! Really useful to keep on top of popular tech.

I was wondering if you could add an Angular Ecosystem section. I see you have Vue and React. Adding Angular to the list would be great!

**Comment by michaelrambeau** [comment]
Hello Benjamin @BBlackwo, thank you for your kind words!
It's a bit late to update the 2017 version of the _Rising Stars_ but for the next version, we could add a section about the Angular eco-system, that's a good idea.
To tell the truth, among the team members, there was nobody familiar with the Angular eco-system.
So if you are interested in the project, you could write the comments related to that new section!

That being said, all data displayed in _Rising Stars_ comes from _Best of JS_ application. So if you want to check what would be the rankings in this category, check this page: https://bestof.js.org/tags/angular/trending/last-12-months
As you can see, there are only 20 projects in the category because we don't follow closely what's happening the Angular community.

Let us know if you find great projects that should be in this category, thank you!

**Comment by BBlackwo** [comment]
Hi @michaelrambeau, sorry for taking so long to get back to you.

Some ideas off the top of my head of Angular libraries you could add are:
- [NgRx](https://github.com/ngrx/platform)
- [Nx](https://github.com/nrwl/nx)
- [Angular CLI](https://github.com/angular/angular-cli)
- [Angular Console](https://github.com/nrwl/angular-console)
- Official list on Angular website: https://angular.io/resources
- Some Angualr component libraries: https://blog.bitsrc.io/11-angular-component-libraries-you-should-know-in-2018-e9f9c9d544ff

As for writing the comments for the Angular section, I don't think I'm up for that at the moment but I appreciate the offer. I'll keep it in mind too.

Thanks!

**Comment by michaelrambeau** [comment]
Hello Benjamin @BBlackwo 
Thank you for the suggestions, the projects you mentioned will be added to _Best of JavaScript_.
I will tell you when it's online.
About the next edition of _Rising Stars_, nothing is planned so far, I will contact you when we work on the project.

**Comment by michaelrambeau** [comment]
Hello @BBlackwo,
Could you please check the `Angular` tag in _Best of JavaScript_?
https://bestofjs.org/tags/angular

You will find 9 more projects, including `Angular CLI`, the most popular project among those you mentioned.
Thank you in advance and feel free to suggest any addition at any time!

**Comment by BBlackwo** [comment]
@michaelrambeau that's great thank you!

**Comment by BBlackwo** [comment]
@michaelrambeau that's great thank you!

**Comment by michaelrambeau** [comment]
Hello Benjamin @BBlackwo ,
We have a draft of the 2018 edition of _Rising Stars_, available at this temporary URL: https://dev--risingstars.netlify.com/2018/en/

Could you have a look, do you have any comment that could be added? (even if it's not related to the TOP 10 projects, anything related to the Angular ecosystem in 2018 would be interesting)

![image](https://user-images.githubusercontent.com/5546996/50641419-34baea80-0fab-11e9-86a2-a784cdcbf77b.png)

Thank you in advance!

**Comment by BBlackwo** [comment]
Looks good @michaelrambeau. 

Version 6 of the CLI brought a heap of [new features](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4). I think the most notable are:
1. Updating your application and it's dependencies with the `update` command.
2. Builders allowing customisation of the underlying webpack config without ejecting which I believe is not available in create-react-app (e.g. [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) and [angular builders](https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21))
3. Another new CLI command, `ng add`, which makes adding new capabilities to your project easy. (e.g. `ng add @angular/material` will install and configure your app to use Angular Material.)
4. Support to generate and build libraries
5. Workspaces containing multiple projects (e.g. a monorepo)

I think at least the first two are worth mentioning :)

**Comment by BBlackwo** [comment]
Interestingly, React, Angular, and Vue all have their CLI and a material design component library in the top 6.

**Comment by michaelrambeau** [comment]
Thank you very much for the insights Benjamin, it's really useful! @BBlackwo 

Could you check again if what I wrote here makes sense (it's the final URL):

https://risingstars.js.org/2018/en/#section-angular

I mentioned the release of Angular 7.
Feel free to adjust the text if you feel inspired :) I'd mention your name. The content comes from here, FYI: https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2018/categories/angular/en.md

**Comment by BBlackwo** [comment]
No worries, Michael. That looks good to me -- good idea to mention Angular 7. In general they're [expecting two major releases every year](https://angular.io/guide/releases#release-frequency) FYI. So next year should be 8 and 9.

The description may be getting a bit long though. I reckon you can cull the bit at the end about Angular 1.

**Comment by BBlackwo** [comment]
Btw @michaelrambeau, I'm keen to know when the final version of this is released for 2018. I hope to share it around the Angular community, as much as I can as it has an Angular ecosystem section this year 🙂

I'm guessing it's not quite final now as I noticed a few bugs relating to missing images and such.

**Comment by michaelrambeau** [comment]
Thank you for your help Benjamin @BBlackwo , I really appreciate it!

I'd like to finish the English version this week-end, in order to release "officially" next week, as soon as possible.

I'm still working on the layout, I've just pushed this version:

https://dev--risingstars.netlify.com/2018/en/

The banner is made of the logos of the trendiest projects of the year.
(the previous version was re-using a picture created for the 2017 version).

Could you let me know about the bugs and missing images you found?

**Comment by BBlackwo** [comment]
You're welcome Michael @michaelrambeau. Thanks for all the work you've put into this 🙂

Sounds good to release next week. The new banner looks good.

I've raised #34 with the missing images.

**Comment by BBlackwo** [comment]
Hey Michael, @michaelrambeau has it been "officially released" yet? =)

**Comment by michaelrambeau** [comment]
Hello Benjamin @BBlackwo ,

Oh, sorry, I should have told you, we can consider it has been released, even if there was not a lot of communication around the release. It was mentioned by the latest edition of "javascriptweekly" newsletter.

There was a last minute addition today: https://github.com/bestofjs/bestofjs-webui/issues/68
