### ISSUE TITLE
Storybook uncategorized in 2019 JS Rising Stars

### ISSUE THREAD

**Issue by shilman** [bestofjs/javascript-risingstars#54]
Great job with the [2019 rising stars](https://risingstars.js.org/2019/en/) summary -- it looks awesome (I love the integrated bar chart in the background of each category!

I maintain [Storybook](https://github.com/storybookjs/storybook), which is one of the top projects overall (just below the fold) but since apparently it's in its own category, it's effectively buried.

Would it be possible to include storybook in the testing category, as it was for StateOfJS? I would  also be very happy if it was considered in the react/vue/angular ecosystems, since it's the top component workshop (and documentation system!) for all three frameworks. 😄

**Comment by michaelrambeau** [comment]
Hello Michael @shilman it's good to see you here!
Tagging projects is not an easy task, _Storybook_ has the following tags in _Best of JavaScript_, as you can see [here](https://bestofjs.org/projects/storybook):

- testing
- react
- vue.js
- angular

![image](https://user-images.githubusercontent.com/5546996/74477657-0a966480-4eef-11ea-898e-24baf99956dd.png)

However, for the _Rising Stars_ project, categories are sometimes a bit different, we filter some projects to avoid some redundancy, but I understand your point of view, _Storybook_ success should be more visible.

I have just fixed the Testing category,  now Storybook is included and visible at position number 2.

![image](https://user-images.githubusercontent.com/5546996/74477346-7cba7980-4eee-11ea-810f-5fa87c559e46.png)

Could you have a look?
Could you provide one or 2 lines of text to describe the main changes about Storybook in 2019, in order to update the comments related to the testing category?
Thank you for your understanding!

**Comment by shilman** [comment]
Hey @michaelrambeau I completely understand and thanks so much for the quick response. I contributed to the first StateOfJS -- it's amazing (and wonderful) to see how far it's all come in the past few years!!

How does this sound for a blurb?

> [Storybook](https://storybook.js.org) is a UI component workshop that provides development, testing, documentation, and a rich addon ecosystem. In 2019 it upgraded to an example format that can be directly imported in [Jest](https://jestjs.io/) and other testing tools.

(Lots of stuff happened in 2019, but that's probably the biggest testing-related change)

**Comment by michaelrambeau** [comment]
Thank you for the burb @shilman it's online!

Speaking of growth, the amazing thing is the success of _Storybook_ and how its scope expanded.

By the way, I'm thinking about a specific tag to find easily projects similar to Storybook (projects that share the concept of visual testing playground for components).

The category would also include:

- Styleguidist (for React and Vue.js)
- React Live https://react-live.netlify.com/
- Playroom https://github.com/seek-oss/playroom

Does it make sense to you, how would you name such a category: "Component Playground" for example?
