### ISSUE TITLE
Images are squashed on mobile

### ISSUE THREAD

**Issue by BBlackwo** [bestofjs/javascript-risingstars#55]
Hi Michael,

I found the images are squashed viewing the weekly issue on my phone.

Maybe on mobile, you could remove the "homepage" link and make the title clickable instead (like you do in the email)? That would give more room for the image.

<img width="410" alt="Screen Shot 2020-05-19 at 4 44 27 am" src="https://user-images.githubusercontent.com/7598058/82248416-732c2c00-998b-11ea-9716-7972411fc84d.png">

**Comment by BBlackwo** [comment]
Or even easier, just remove the image on mobile?

**Comment by michaelrambeau** [comment]
Thank you @BBlackwo I will fix as soon as possible!

Also, since the buttons "GitHub" and "Homepage" takes a lot of place I could move them below the description, on mobile, it's an other option.

**Comment by michaelrambeau** [comment]
Hello @BBlackwo !
Could you check again, I've adjusted the layout?
By the way you created the issue on "Rising Stars" project (the annual round-up) but the issue was about the weekly newsletter, I guess: https://weekly.bestofjs.org/

## Sharing screenshots 

### 375 px

![image](https://user-images.githubusercontent.com/5546996/82744955-15984500-9dba-11ea-8b14-4cc64dc75207.png)

### 520 px

![image](https://user-images.githubusercontent.com/5546996/82744981-4a0c0100-9dba-11ea-9a5c-40b227a40058.png)

**Comment by BBlackwo** [comment]
Hi @michaelrambeau,
It looks much better now. 🙂 

Woops, yes I should have raised it on the [bestofjs-weekly](https://github.com/BBlackwo/bestofjs-weekly) repo sorry.

I've done a PR to increase the left padding slightly https://github.com/bestofjs/bestofjs-weekly/pull/7.

**Comment by BBlackwo** [comment]
Closing this as it's fixed now.
